import type { Job } from "../types/TypeChecks";

export const dummyJobs: Job[] = [
  {
    _id: "job-001",
    title: "Senior Mathematics Teacher",
    institutionName: "Cedar Heights School",
    institutionImage: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=120&h=120&fit=crop&crop=center",
    location: "Lagos",
    employmentType: "FULL_TIME",
    level: "INTERMEDIATE",
    subject: "Mathematics",
    salaryRange: "₦180,000 – ₦260,000/mo",
    postedAt: "2d ago",
    applicants: 14,
    slots: 2,
    featured: true,
    description:
      "Lead junior secondary mathematics classes and support exam preparation. You'll deliver structured lesson plans, conduct weekly assessments, and provide personalised feedback to help students achieve outstanding WAEC and NECO results.",
  },
  {
    _id: "job-002",
    title: "English Language Tutor",
    institutionName: "Brightpath Learning Centre",
    institutionImage: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=120&h=120&fit=crop&crop=center",
    location: "Abuja",
    employmentType: "PART_TIME",
    level: "EXPERT",
    subject: "English Language",
    salaryRange: "₦8,000 – ₦12,000/session",
    postedAt: "4d ago",
    applicants: 9,
    slots: 1,
    featured: false,
    description:
      "Teach small-group English lessons for senior students preparing for WAEC and internal assessments. Strong command of grammar, comprehension, and essay writing is essential for this role.",
  },
  {
    _id: "job-003",
    title: "Physics Instructor",
    institutionName: "Northfield College",
    institutionImage: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&h=120&fit=crop&crop=center",
    location: "Port Harcourt",
    employmentType: "ROTATIONAL",
    level: "EXPERT",
    subject: "Physics",
    salaryRange: "₦15,000 – ₦22,000/session",
    postedAt: "6d ago",
    applicants: 6,
    slots: 2,
    featured: true,
    description:
      "Deliver rotational physics sessions across two campuses with hands-on lab supervision. You will design experiments, guide students through practical work, and ensure compliance with safety protocols.",
  },
  {
    _id: "job-004",
    title: "Primary Class Teacher",
    institutionName: "Heritage Primary School",
    institutionImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=120&h=120&fit=crop&crop=center",
    location: "Ibadan",
    employmentType: "FULL_TIME",
    level: "BEGINNER",
    subject: "Primary Education",
    salaryRange: "₦120,000 – ₦180,000/mo",
    postedAt: "1w ago",
    applicants: 21,
    slots: 3,
    featured: false,
    description:
      "Manage a vibrant primary classroom, prepare structured lesson notes, and coordinate regular parent-teacher communication. Ideal for passionate educators who enjoy nurturing foundational learning.",
  },
  {
    _id: "job-005",
    title: "Computer Science Teacher",
    institutionName: "FutureTech Academy",
    institutionImage: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=120&h=120&fit=crop&crop=center",
    location: "Lagos",
    employmentType: "PART_TIME",
    level: "INTERMEDIATE",
    subject: "Computer Science",
    salaryRange: "₦10,000 – ₦18,000/session",
    postedAt: "1w ago",
    applicants: 11,
    slots: 1,
    featured: false,
    description:
      "Teach coding fundamentals, data structures, and guide students through practical web development projects. Experience with Python or JavaScript is required; prior classroom experience is a plus.",
  },
  {
    _id: "job-006",
    title: "Chemistry Teacher",
    institutionName: "Greenfield Secondary",
    institutionImage: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=120&h=120&fit=crop&crop=center",
    location: "Enugu",
    employmentType: "ROTATIONAL",
    level: "INTERMEDIATE",
    subject: "Chemistry",
    salaryRange: "₦12,000 – ₦18,000/session",
    postedAt: "2w ago",
    applicants: 8,
    slots: 2,
    featured: false,
    description:
      "Support chemistry classes and practical experiments on a weekly rotational schedule. Must be comfortable managing a laboratory environment and inspiring students through real-world applications.",
  },
  {
    _id: "job-007",
    title: "Biology & Health Science Teacher",
    institutionName: "Graceland International School",
    institutionImage: "https://images.unsplash.com/photo-1492538368677-f6e0afe31dcc?w=120&h=120&fit=crop&crop=center",
    location: "Lagos",
    employmentType: "FULL_TIME",
    level: "EXPERT",
    subject: "Biology",
    salaryRange: "₦200,000 – ₦300,000/mo",
    postedAt: "3d ago",
    applicants: 17,
    slots: 1,
    featured: true,
    description:
      "Lead biology and health science classes for SS1–SS3. The ideal candidate holds a B.Sc. in Biology or related field, has 3+ years of classroom experience, and is skilled at preparing students for competitive examinations.",
  },
  {
    _id: "job-008",
    title: "French Language Teacher",
    institutionName: "Alliance Grammar School",
    institutionImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=120&h=120&fit=crop&crop=center",
    location: "Abuja",
    employmentType: "PART_TIME",
    level: "BEGINNER",
    subject: "French",
    salaryRange: "₦7,000 – ₦10,000/session",
    postedAt: "5d ago",
    applicants: 4,
    slots: 1,
    featured: false,
    description:
      "Deliver engaging French language lessons to junior secondary students two days a week. Native or near-native French fluency required. A fun, communicative teaching style is highly valued.",
  },
  {
    _id: "job-009",
    title: "Economics Teacher",
    institutionName: "Premier Secondary Academy",
    institutionImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=120&h=120&fit=crop&crop=center",
    location: "Kano",
    employmentType: "FULL_TIME",
    level: "INTERMEDIATE",
    subject: "Economics",
    salaryRange: "₦150,000 – ₦220,000/mo",
    postedAt: "1w ago",
    applicants: 12,
    slots: 1,
    featured: false,
    description:
      "Teach economics to SS1–SS3 classes with a focus on current Nigerian and global economic realities. Ability to simplify complex macroeconomic concepts for teenage learners is a must.",
  },
];

export const dashboardStats = [
  {
    label: "Open Jobs",
    value: "42",
    trend: "+12%",
  },
  {
    label: "Applications",
    value: "186",
    trend: "+24%",
  },
  {
    label: "Matched Teachers",
    value: "78",
    trend: "+9%",
  },
  {
    label: "Pending Reviews",
    value: "16",
    trend: "-3%",
  },
];

export const recentApplications = [
  {
    teacher: "Amaka Nwosu",
    role: "Mathematics Teacher",
    status: "Shortlisted",
    time: "Today",
  },
  {
    teacher: "Tunde Balogun",
    role: "Physics Instructor",
    status: "Pending",
    time: "Yesterday",
  },
  {
    teacher: "Ifeoma Okeke",
    role: "English Language Tutor",
    status: "Accepted",
    time: "2d ago",
  },
];
